django_invoice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fact_app.urls'))
]

if settings.DEBUG:

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fact_app/urls.py
from django.urls import path
from .import views

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),
    path('add-customer', views.AddCustomerView.as_view(), name='add-customer'),
    path('add-invoice', views.AddInvoiceView.as_view(), name='add-invoice'),
    path('view-invoice/<int:pk>', views.InvoiceVisualizationView.as_view(), name='view-invoice'),
    path('invoice_pdf/<int:pk>', views.get_invoice_pdf, name='invoice_pdf')
]

fact_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    """"
    Name: Customer model definition
    """

    SEX_TYPES =(
        ('M', 'Masculin'),
        ('F', 'Feminin')
    )

    name =models.CharField(max_length=132)
    email =models.EmailField()

    phone= models.CharField(max_length=132)
    address = models.CharField(max_length=64)
    sex = models.CharField(max_length=1, choices=SEX_TYPES)
    age = models.CharField(max_length=12)
    city = models.CharField(max_length=16)
    zip_code=models.CharField(max_length=16)
    created_date = models.DateTimeField(auto_now_add=True)
    save_by = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"
    def __str__(self):
        return self.name
    

class Invoice(models.Model):
        """"
        Name: Invoice modek definition
        author:loic@gmail.com
        """

        INVOICE_TYPE=(
            ('R', 'RECEIPT'),
            ('P', 'PROFORMA INVOICE'),
            ('I', 'INVOICE')
        )

        customer =models.ForeignKey(Customer, on_delete=models.PROTECT)

        save_by = models.ForeignKey(User, on_delete=models.PROTECT)
        invoice_date_time = models.DateTimeField(auto_now_add=True)

        total = models.DecimalField(max_digits=10000, decimal_places=2)
        last_update_date = models.DateTimeField(null=True, blank=True)
        paid = models.BooleanField(default=False)
        invoice_type = models.CharField(max_length=1, choices=INVOICE_TYPE)

        comments=models.TextField(null=True, max_length=1000, blank=True)
        class Meta:
            verbose_name="Invoice"
            verbose_name_plural="Invoices"

        def __str__(self):
            return f"{self.customer.name} {self.invoice_date_time}"
        @property
        def get_total(self):
             articles = self.article_set.all()
             total = sum(article.get_total or 0 for article in articles)
             return total
             #total de tous les articles de la facture

class Article(models.Model):
     """"
     Name:Article model definition
     Description:
     Author:Loic @gmail.com
     """
     invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)

     name=models.CharField(max_length=32)
     quantity=models.IntegerField()
     unit_price=models.DecimalField(max_digits=1000, decimal_places=2)

     total=models.DecimalField(max_digits=1000, decimal_places=2)  

     class Meta:
          verbose_name='Article'
          verbose_name_plural="Articles"
     @property 
     def get_total(self):
         total =self.quantity * self.unit_price
         return total 
         #total de chaque article

        

templates/Base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
  <!--jquery-->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <title>Facture</title>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">INVOICE SYSTEM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
      
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                      Languages
                    </a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">English</a>
                      <a class="dropdown-item" href="#">French</a>
                  </li>
                  
                </ul>
                
              </div>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
    
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    More option
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'home' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'add-customer' %}">Add customer</a>
                    <a class="dropdown-item" href="{% url 'add-invoice' %}">Add invoice</a>
                    <a class="dropdown-item" href="#">Add admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Statistic</a>
                  </div>
                </li>
                
              </ul>
              
            </div>
          </nav>
    </header>

    <div class="container">
      <div class="Wrapper">
        <br>
        {% for message in messages %}
        <div class="alert {{message.tags}} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" arial-label="Close">
            <span arial-hidden="true">&times;</span>
          </button>
          {{ message|safe }}
        </div>
        {% endfor %}
      </div>
    </div>


    <div class="container">
        {% block content %}

        {% endblock content %}


    </div>
    <footer class="bg-light text-center text-dark">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        invoice system © 2024 copyright:
        <a href="#">Loic jospin</a>
      </div>

    </footer>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</body>
</html>

templates/add_customer.html
{% extends "Base.html" %}

{% block content %}

<br><br><br>
<h1 class="text-capitalize text-center mx-10 bg-dark text white"> Reagister a new customer</h1>
<form action="" method="post">
     {% csrf_token %} 
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="name">Name</label>
            <input name="name" type="text" required class="form-control" id="name" placeholder="customer first and last name">
        </div>

        <div class="form-group col-md-4">
            <label for="email">Email</label>
            <input name="email" type="email" required class="form-control" id="email" placeholder="customer email">
        </div>

        <div class="form-group col-md-2">
            <label for="phone">Phone</label>
            <input name="phone" type="number" required class="form-control" id="phone" placeholder="customer phone number">
        </div>
    </div>    

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="sex">Sex</label>
                <select name="sex" class="form-control" required id="sex">
                    <option>Choose the gender.. </option>
                    <option value="M">masculin</option>
                    <option value="F">Feminin</option>
                </select>
            </div>

            <div class="form-group col-md-6">
                <label for="age">Age</label>
                <select name="age" class="form-control" required id="age">
                    <option>Choose the age range.. </option>
                    <option value="0-15">0-15</option>
                    <option value="15-25">15-25</option>
                </select>
            </div>

            </div>

            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="address">Address</label>
                    <input name="address" type="text" required class="form-control" id="address" placeholder="Customer address">
                </div>

        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="city">City</label>
                <input name="city" type="text" required class="form-control" id="city" placeholder="customer city">
            </div>

            <div class="form-group col-md-6">
                <label for="zip">Zip code</label>
                <input name="zip" type="text" required class="form-control" id="zip" placeholder="customer zip code">
            </div>
        </div>

        <button type="submit" class="btn-primary">Save</button>
    
</form>

<br><br><br>

{% endblock content %}

templates/index.html
{% extends "Base.html" %}
{% load static %}




{% block content %}
<br><br>

<div class="row">
   <a href="{% url 'add-invoice' %}" class="btn col-md-4 btn-primary">
      Register a new invoice <span class="badge text-bg-secondary"></span>
   </a>

   <a href='#' class="col-md-4">
      <span class="badge text-bg-secondary"></span>
   </a>

   <a href="{% url 'add-customer' %}" class="btn col-md-4 btn-primary">
       Register a new customer <span class="badge text-bg-secondary"></span>
   </a>

</div>

<br> <br>

<div class="form-group ">
   <input id="search" class="form-control" type="text" placeholder="Search....">
</div>

<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">CUSTOMERS NAME</th>
            <th scope="col">DATE</th>
            <th scope="col">TOTAL</th>
            <th scope="col">PAID</th>
            <th scope="col">TYPE OF INVOICE</th>
            <th scope="col">ACTION</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if invoices %}
         {% for facture in invoices %}
         <tr>
            <th scope="row">{{ facture.pk }}</th>
            <td>{{facture.customer.name}}</td>
            <td>{{facture.invoice_date_time}}</td>
            <td>{{ facture.get_total }}</td>
            <td>
               {% if facture.paid %}
               <img src="{% static 'image/icon-yes.svg' %}" alt="True">
               {% else %}
               <img src="{% static 'image/icon-no.svg' %}" alt="False">
               {% endif %}
            </td>
            <td>{{facture.get_invoice_type_display }}</td>
            <td>
               <a href="{% url 'view-invoice' pk=facture.pk %}" title="Detail" class="badge text-white bg-success">View</a>

               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                  class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}"
                  data-customer="{{facture.customer.name}}">Delete
               </button>

               <button id="btn-invoice-mod" type="button" data-toggle="modal" title="Modifier" data-target="#modifier"
                  data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                  class="badge text-dark bg-warning"> Modify
               </button>
            </td>
         </tr>

         {% endfor %}

         {% if invoices.has_other_pages %}
         <div class="btn-group" role="group" aria-label="Item pagination">
            {% if invoices.has_previous %}
            <a href="?page={{ invoices.previous_page_number }}" class="btn btn-outline-warning">&laquo;</a>
            {% endif %}

            {% for page in invoices.paginator.page_range %}
               {% if page == invoices.number %}
                  <a href="?page={{ page }}" class="btn btn-outline-warning active">{{ page }}</a>
                  {% else %}
                  <a href="?page={{ page }}" class="btn btn-outline-warning">{{ page }}</a>
               {% endif %}
            {% endfor %}
            {% if invoices.has_next %}
            <a href="?page={{ invoices.next_page_number }}" class="btn btn-outline-warning">&laquo;</a>
            {% endif %}


         </div>
         {% endif %}

         {% else %}
         
         <p class="text-center text-white">No invoice found.</p>
         {% endif %}


      </tbody>

   </table>
</div>

<!-- Modal modifier -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">Modification</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">

               <input name="id_modified" type="hidden" id="id_modified">

               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id"> This bill has been paid?</strong></label>

               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">Yes</label>

               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">No</label><br>

            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <button type="submit" class="btn btn-primary">Save</button>
            </div>
         </form>
      </div>
   </div>
</div>
<!-- end modal-->

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Delete Invoice</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Are you sure you want to delete the invoice  ?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
               </div>
            </form>
         </div>

      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">

   // modification

   $(document).on('click', '#btn-invoice-mod', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);

   })

   // deleting of invoice

   $(document).on('click', '#btn-invoice-sup', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);

   })



</script>


<script>

   $(document).ready(function(){
      $("#search").on("keyup", function(){
         var value = $(this).val().toLowerCase();
         $("#myTable tr").filter(function(){
            $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value)>-1)
         });
      });
   });

</script>



{% endblock %}

templates/invoice-template.html
{% extends "Base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="#" class="invoice-logo">
    									Loic Jospin Market
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Loic Jospin Market, Biyem-assi<br>
    									Cameroon, yaounde<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}, Cameroon
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date}}</div>
    									</div>
    								</div>													
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-body">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}  
                                              
    											<tr>

                                                   

                                                    <td>
    													{{ article.name }}
    													
    												</td>

													<td>
    													{{ article.id }}
    													
    												</td>

													<td>
    													{{ article.quantite }}
    													
    												</td>

													<td>
    													{{ article.prix_u }}
    													
    												</td>

													<td>
    													{{ article.get_total }}
    													
    												</td>

                                                    
    												
    											</tr>
                                               {% endfor %} 
    											
    											
    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>			
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td> 
                                                            PAID:                    

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'image/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'image/icon-no.svg' %}" alt="False">
   
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-footer">
    						Thank you for your purchase .
    					</div>
    
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}

templates/invoice.html
{% extends "Base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="{% url 'invoice_pdf' pk=obj.pk %}" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="#" class="invoice-logo">
    									Loic Jospin Market
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Loic Jospin Market, Biyem-assi<br>
    									Cameroon, yaounde<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}, Cameroon
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date_time}}</div>
    									</div>
    								</div>													
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-body">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Products</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}  
                                              
    											<tr>

                                                   

                                                    <td>
    													{{ article.name }}
    													
    												</td>

													<td>
    													{{ article.id }}
    													
    												</td>

													<td>
    													{{ article.quantity }}
    													
    												</td>

													<td>
    													{{ article.unit_price }}
    													
    												</td>

													<td>
    													{{ article.get_total }}
    													
    												</td>

                                                    
    												
    											</tr>
                                               {% endfor %} 
    											
    											
    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>			
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>{{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td> 
                                                            PAID:                    

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'image/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'image/icon-no.svg' %}" alt="False">
   
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-footer">
    						Thank you for your purchase .
    					</div>
    
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}